const partnersList = [
  {
    id: 1,
    img: "/../public/partners/p1.png",
    width: "152",
    height: "72",
    path: "/",
    alt: "Moon Studios",
  },
  {
    id: 2,
    img: "/../public/partners/p2.png",
    width: "224",
    height: "56",
    path: "/",
    alt: "Scopely",
  },
  {
    id: 3,
    img: "/../public/partners/p3.png",
    width: "209",
    height: "76",
    path: "/",
    alt: "Roomful",
  },
  {
    id: 4,
    img: "/../public/partners/p4.png",
    width: "243",
    height: "58",
    path: "/",
    alt: "Rogue Sun",
  },
  {
    id: 5,
    img: "/../public/partners/p5.png",
    width: "65",
    height: "76",
    path: "/",
    alt: "Play Maker",
  },
  {
    id: 6,
    img: "/../public/partners/p6.png",
    width: "164",
    height: "89",
    path: "/",
    alt: "One Signal",
  },
  {
    id: 7,
    img: "/../public/partners/p7.png",
    width: "109",
    height: "107",
    path: "/",
    alt: "Plawius",
  },
  {
    id: 8,
    img: "/../public/partners/p8.png",
    width: "243",
    height: "58",
    path: "/",
    alt: "Soomla",
  },
  {
    id: 9,
    img: "/../public/partners/p9.png",
    width: "240",
    height: "54",
    path: "/",
    alt: "Unibit",
  },
  {
    id: 10,
    img: "/../public/partners/p10.png",
    width: "129",
    height: "212",
    path: "/",
    alt: "Blackwood games",
  },
  {
    id: 11,
    img: "/../public/partners/p11.png",
    width: "245",
    height: "43",
    path: "/",
    alt: "Mobik ts",
  },
];

export default partnersList;
