const vacations = [
  {
    id: 1,
    title: "Unity Developer 1",
    requirements: [
      "Experience as a Technical Artist1;",
      "Experience with C#/Unity programming1;",
      "Proficient in Autodesk Maya, 3DS Max, Photoshop, Substance, etс.1;",
      "Confident knowledge of Unity graphics pipeline1;",
      "Development 2D and 3D games1;",
      "Experience with mobile/web1;",
      "Experience with shader development in game engines1;",
      "Experience with Profiling/Debugging and Optimization by CPU, GPU, memory and build size.1",
    ],
    preferences: [
      "Experience with consoles NSwitch/Xbox/PS41;",
      "Experience with shader languages HLSL/GLSL1;",
      "Experience with unit, behaviour, integration testing1;",
      "Experience with Jenkins/TeamCity1;",
      "Worked on/created large frameworks and projects.1",
    ],
    responsibilities: [
      "Work with artists and engineers to create and implement art and technical solutions1;",
      "Support artists and engineers in the use of the 3D art pipeline and tool-chains1;",
      "Provide hands-on support to artists and engineers in regard to asset performance and validation1;",
      "Solve challenging technical issues in the 3D asset pipeline1;",
      "Collaborate with engineers and testers to diagnose and resolve in-game problems1;",
      "Collaborate with partner studios to share technology, workflows and best practices1;",
      "Able to work and communicate effectively in a fast-paced environment where goals and requirements may constantly be changing1;",
      "Committed to learning and sharing with the team to help achieve overall goals.1",
    ],
  },
  {
    id: 2,
    title: "Unity Developer 2",
    requirements: [
      "Experience as a Technical Artist2;",
      "Experience with C#/Unity programming2;",
      " Proficient in Autodesk Maya, 3DS Max, Photoshop, Substance, etс.2;",
      "Confident knowledge of Unity graphics pipeline2;",
      "Development 2D and 3D games2;",
      "Experience with mobile/web2;",
      "Experience with shader development in game engines2;",
      "Experience with Profiling/Debugging and Optimization by CPU, GPU, memory and build size.2",
    ],
    preferences: [
      "Experience with consoles NSwitch/Xbox/PS42;",
      "Experience with shader languages HLSL/GLSL2;",
      "Experience with unit, behaviour, integration testing2;",
      "Experience with Jenkins/TeamCity2;",
      "Worked on/created large frameworks and projects.2",
    ],
    responsibilities: [
      "Work with artists and engineers to create and implement art and technical solutions2;",
      "Support artists and engineers in the use of the 3D art pipeline and tool-chains2;",
      "Provide hands-on support to artists and engineers in regard to asset performance and validation2;",
      "Solve challenging technical issues in the 3D asset pipeline2;",
      "Collaborate with engineers and testers to diagnose and resolve in-game problems2;",
      "Collaborate with partner studios to share technology, workflows and best practices2;",
      "Able to work and communicate effectively in a fast-paced environment where goals and requirements may constantly be changing2;",
      "Committed to learning and sharing with the team to help achieve overall goals.",
    ],
  },
  {
    id: 3,
    title: "Unity Developer 3",
    requirements: [
      "Experience as a Technical Artist3;",
      "Experience with C#/Unity programming3;",
      "Proficient in Autodesk Maya, 3DS Max, Photoshop, Substance, etс.3;",
      "Confident knowledge of Unity graphics pipeline3;",
      "Development 2D and 3D games3;",
      "Experience with mobile/web3;",
      "Experience with shader development in game engines3;",
      "Experience with Profiling/Debugging and Optimization by CPU, GPU, memory and build size.3",
    ],
    preferences: [
      "Experience with consoles NSwitch/Xbox/PS43;",
      "Experience with shader languages HLSL/GLSL3;",
      "Experience with unit, behaviour, integration testing3;",
      "Experience with Jenkins/TeamCity3;",
      "Worked on/created large frameworks and projects.3",
    ],
    responsibilities: [
      "Work with artists and engineers to create and implement art and technical solutions3;",
      "Support artists and engineers in the use of the 3D art pipeline and tool-chains3;",
      "Provide hands-on support to artists and engineers in regard to asset performance and validation3;",
      "Solve challenging technical issues in the 3D asset pipeline3;",
      "Collaborate with engineers and testers to diagnose and resolve in-game problems3;",
      "Collaborate with partner studios to share technology, workflows and best practices3;",
      "Able to work and communicate effectively in a fast-paced environment where goals and requirements may constantly be changing3;",
      "Committed to learning and sharing with the team to help achieve overall goals.3",
    ],
  },
];

export default vacations;
