import HeroBlock from "../../../components/HeroBlock/heroBlock";
import ContentTextBlock from "../../../components/ContentTextBlock/contentTextBlock";
import Looking from "../../../components/Looking/looking";
import Contacts from "../../../components/Contacts/contacts";

import image from "../../../public/Technologies/android.png";

export const metadata = {
  title: "Android",
  description: "Generated by create next app",
};

const Android = () => {
  return (
    <>
      <HeroBlock title="android technologies" img={image} alt="Apple" />
      <ContentTextBlock />
      <Looking />
      <ContentTextBlock />
      <Contacts />
    </>
  );
};

export default Android;
