export const metadata = {
  title: "Android",
  description: "Generated by create next app",
};

const Android = () => {
  return (
    <>
      <h1>Android</h1>
    </>
  );
};

export default Android;
